version: '3.4'
services:
  frontend:
    build:
      target: build_and_test
      context: ./frontend
  features:
    build:
      context: .
    depends_on:
      - backend
      - frontend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
      - CAPYBARA_APP_HOST=http://frontend:4200
  backend:
    command: "bin/rails server -b 0.0.0.0 --environment=fullstack"
