version: '3.4'
services:
  frontend:
    environment:
      - PIWIK_URL=http://piwik
  sidekiq:
    image: rundfunkmitbestimmen/backend:latest
    build:
      context: ./backend
    depends_on:
      - redis
      - db
    command: bundle exec sidekiq
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  mariadb:
    image: mariadb:latest
  matomo:
    image: matomo:fpm-alpine
    depends_on:
      - mariadb
