version: '3.4'
services:
  frontend:
    environment:
      - PORT=4200
  sidekiq:
    image: rundfunkmitbestimmen/sidekiq:latest
    build:
      context: ./backend
    depends_on:
      - redis
      - db
    command: bundle exec sidekiq
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres
      - REDIS_URL=redis://redis:6379
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
