version: '3'
services:
  frontend:
    volumes:
      - ./frontend/:/frontend/
      - node_modules:/frontend/node_modules
    tty: true
    stdin_open: true
  backend:
    volumes:
      - ./backend:/backend
    tty: true
    stdin_open: true

volumes:
  node_modules:
